# Generated by Django 5.2.6 on 2025-09-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mail_date", models.DateTimeField(verbose_name="date sent")),
                ("mail_from", models.CharField(max_length=200)),
                ("mail_subject", models.CharField(max_length=200)),
                ("mail_text", models.CharField(max_length=1000)),
            ],
        ),
    ]
