# Generated by Django 5.2.6 on 2025-09-24 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reply_date", models.DateTimeField(auto_now_add=True)),
                (
                    "reply_from",
                    models.CharField(
                        default="amrstestemail4dev@gmail.com", max_length=255
                    ),
                ),
                ("reply_to", models.CharField(max_length=255)),
                ("reply_text", models.TextField()),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="emails.emailmessages",
                    ),
                ),
            ],
        ),
    ]
