# Generated by Django 5.2.6 on 2025-09-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_emailreply"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessages",
            name="message_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="emailmessages",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="emailreply",
            name="in_reply_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="emailreply",
            name="message_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
