# Generated by Django 5.2.6 on 2025-09-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_emailmessages_message_id_emailmessages_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailmessages",
            name="message_id",
        ),
        migrations.RemoveField(
            model_name="emailreply",
            name="in_reply_to",
        ),
        migrations.RemoveField(
            model_name="emailreply",
            name="message_id",
        ),
    ]
