# Generated by Django 5.2.6 on 2025-09-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0004_remove_emailmessages_message_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessages",
            name="mail_reply_to",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailmessages",
            name="message_uid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
