# Generated by Django 5.2.6 on 2025-09-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0005_emailmessages_mail_reply_to_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailmessages",
            old_name="message_uid",
            new_name="message_id",
        ),
        migrations.RemoveField(
            model_name="emailmessages",
            name="mail_reply_to",
        ),
    ]
