# Generated by Django 5.2.6 on 2025-09-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0006_rename_message_uid_emailmessages_message_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailmessages",
            name="message_id",
        ),
        migrations.AddField(
            model_name="emailmessages",
            name="ticket_number",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
