# Generated by Django 5.2.6 on 2025-09-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_remove_emailmessages_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessages',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
